// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4M8BaUS0c4l53mD1S1fAYkJhEYgZ5Tyw',
    appId: '1:10180692151:web:a444b5aab68cb907a2a532',
    messagingSenderId: '10180692151',
    projectId: 'kwikwinotes',
    authDomain: 'kwikwinotes.firebaseapp.com',
    storageBucket: 'kwikwinotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGLTjVYAbyacgVarXekWgWWtRqT4babko',
    appId: '1:10180692151:android:4cefeea8266cfce0a2a532',
    messagingSenderId: '10180692151',
    projectId: 'kwikwinotes',
    storageBucket: 'kwikwinotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTdU0WkA6bk8pfsBTIE2CgYHf9q2jBGho',
    appId: '1:10180692151:ios:a89a6946905dd5a7a2a532',
    messagingSenderId: '10180692151',
    projectId: 'kwikwinotes',
    storageBucket: 'kwikwinotes.appspot.com',
    iosBundleId: 'com.example.kwikwinotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTdU0WkA6bk8pfsBTIE2CgYHf9q2jBGho',
    appId: '1:10180692151:ios:1ce7d8166851f248a2a532',
    messagingSenderId: '10180692151',
    projectId: 'kwikwinotes',
    storageBucket: 'kwikwinotes.appspot.com',
    iosBundleId: 'com.example.kwikwinotes.RunnerTests',
  );
}
